### Numpy

1.Numerical Python
2.Data Should be in the form of array.
3.Elements present in array should be same data type

Library

In [2]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [3]:
import numpy as np

In [6]:
#How to define array

import numpy as np
arr=np.array(1)
print(arr)

1


### How to create one dimenstion array

In [25]:
import numpy as np
arr4=np.array([1,3,6])
print(arr4)

[1 3 6]


In [26]:
arr4.shape

(3,)

In [8]:
# to check the data type
print(type(arr))

<class 'numpy.ndarray'>


### How to create two dimenstion array

In [10]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [11]:
print(type(arr1))

<class 'numpy.ndarray'>


In [12]:
# # dimension
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
import numpy as np
arr1=np.array([[1,2,3],[4.6,5+8j,6]])
print(arr1)

[[1. +0.j 2. +0.j 3. +0.j]
 [4.6+0.j 5. +8.j 6. +0.j]]


In [ ]:
# how to convert list into array

In [16]:
import numpy as np
list1=[1,3,5]
result=np.array([list1])
print(result)

[[1 3 5]]


In [18]:
import numpy as np
list1=[1,3,5]
list2=[4,6,7]
result=np.array([list1,list2])
print(result)

[[1 3 5]
 [4 6 7]]


In [ ]:
# Shape

In [21]:
import numpy as np
list3=[1,3,5]
list4=[4,6,7]
result=np.array([list3,list4])
print(result)


[[1 3 5]
 [4 6 7]]


In [23]:
result.shape

(2, 3)

In [27]:
result.shape=(3,2)

In [28]:
result

array([[1, 3],
       [5, 4],
       [6, 7]])

In [29]:
result.shape

(3, 2)

In [30]:
#reshape the array
import numpy as np
list3=[1,3,5]
list4=[4,6,7]
result=np.array([list3,list4])
print(result)


[[1 3 5]
 [4 6 7]]


In [31]:
result.reshape(3,2)

array([[1, 3],
       [5, 4],
       [6, 7]])

In [35]:
# zeros

In [39]:
import numpy as np
x=np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [40]:
x.shape

(5,)

In [43]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
# ones

In [45]:
import numpy as np
x=np.ones(3)
print(x)

[1. 1. 1.]


In [47]:
import numpy as np
x=np.ones([3,3])
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [48]:
new_arr=x.reshape(9,1)

In [49]:
new_arr

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [52]:
a=new_arr.reshape(3,3)

In [53]:
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### range funcnction 

In [56]:
my_range=range(1,5)
print(my_range)
a=list(my_range)
print(a)

range(1, 5)
[1, 2, 3, 4]


In [58]:
my_range=range(1,10,2)
print(my_range)
a=tuple(my_range)
print(a)

range(1, 10, 2)
(1, 3, 5, 7, 9)


### arange

In [59]:
import numpy as np
x=np.arange(1,5)
print(x)

[1 2 3 4]


In [60]:
import numpy as np
x=np.arange(1,10,3)
print(x)

[1 4 7]


### slice

In [68]:
import numpy as np
a=np.arange(10)
print(a)
s=slice(2,7,2)
print(a[s])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [69]:
import numpy as np
a=np.arange(10)
print(a)
s=slice(1,7,2)
print(a[s])

[0 1 2 3 4 5 6 7 8 9]
[1 3 5]


In [ ]:
# Multiplication in arrays

In [72]:
a=np.array([1,2,3])
b=np.array([10,20,30])
result=a*b
print(result)

[10 40 90]


In [ ]:
# Addition of numbers in arrays

In [73]:
a=np.array([1,2,3])
b=np.array([10,20,30])
result=a+b
print(result)

[11 22 33]


#### append in list

In [76]:
list1=[1,2]
list1.append(4)
print(list1)

[1, 2, 4]


In [77]:
#insert
list1=[1,2]
list1.insert(1,'str')
print(list1)

[1, 'str', 2]


#### append

In [ ]:
# Add the new elements into given array

In [88]:
import numpy as np
a=np.array([100,200,300])
np.append(a,[50,60])

array([100, 200, 300,  50,  60])

### insert()

In [92]:
import numpy as np
a=np.array([100,200,300])
np.insert(a,2,60)

array([100, 200,  60, 300])

### delete()

In [99]:
# For delete the elements from array we must provide the index which value we wants to remove

In [98]:
import numpy as np
a=np.array([100,200,300])
np.delete(a,2)

array([100, 200])

### pop()

In [103]:
import numpy as np
a=np.array([100,200,300,400])
np.pop([3])

AttributeError: module 'numpy' has no attribute 'pop'

In [106]:
import numpy as np
a=np.array([100,200,300,400])
np.remove(1)

AttributeError: module 'numpy' has no attribute 'remove'

In [107]:
set1={1,6,8}
set1.pop()

8

In [109]:
set2={1,6,8}
set2.remove(6)
set2

{1, 8}

In [112]:
#char 

In [124]:
import numpy as np
a=np.char.add('Data','Scientist')
a


array('DataScientist', dtype='<U13')